import Link from "next/link";
import { ArrowUpRight, Package, ScanLine, Handshake, ShieldCheck, Globe2, Heart } from "lucide-react";
import { NavHeader } from "@/components/public/nav-header";
import { SiteFooter } from "@/components/public/site-footer";
export default function AboutPage() {
  return <div className="min-h-screen"><NavHeader /><main>
    <section className="secondary-hero bg-brand-forest px-5 py-20 text-white sm:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-2"><div><p className="section-kicker !text-[#c7f36b]">A little closer, every day</p><h1 className="mt-6 text-5xl font-medium leading-[1.08] tracking-[-.05em] sm:text-6xl">Behind every parcel,<br />there’s a person.</h1><p className="mt-7 max-w-lg leading-8 text-white/65">A business taking its next step. A thoughtful gift. Something someone is counting on. At Diplomaxdelivery, that’s what keeps us moving.</p></div><div className="about-parcel" aria-hidden="true"><div className="parcel-top" /><div className="parcel-front"><Package size={58} strokeWidth={1} /><span>HANDLED WITH CARE</span></div><div className="parcel-side" /><span className="parcel-caption">More than a package.</span></div></div></section>
    <section className="mx-auto grid max-w-7xl gap-12 px-5 py-24 sm:px-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="section-kicker">Our purpose</p><h2 className="section-title mt-4">Make distance<br />feel smaller.</h2></div><div><p className="text-xl leading-9">We’re building a delivery experience around a simple idea: sending something should feel straightforward, and following its journey should feel reassuring.</p><p className="mt-6 leading-8 text-muted-foreground">From your first enquiry to the latest shipment update, our focus is on clear information, careful coordination, and practical support. Whether you’re sending one parcel or planning regular deliveries, we’ll help you work out the next step.</p></div></section>
    <section className="journey-section px-5 py-24 sm:px-8"><div className="mx-auto max-w-7xl"><p className="section-kicker">What guides us</p><h2 className="section-title mt-4">Good delivery starts<br />with good principles.</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{[{icon: ScanLine,title:"Clarity at every step",text:"Useful shipment information, accessible tracking, and a clear way to get help."},{icon: Heart,title:"Care in the details",text:"Every parcel matters to someone. That perspective shapes how we approach each journey."},{icon: Handshake,title:"A partnership that fits",text:"We start by understanding what you need to move, where it needs to go, and what matters most."}].map(({icon: Icon,title,text})=><div key={title} className="rounded-3xl border bg-card p-8"><Icon size={28} strokeWidth={1.5} className="text-primary" /><h3 className="mt-8 text-xl font-semibold tracking-tight">{title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{text}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="grid gap-12 lg:grid-cols-2"><div><p className="section-kicker">People behind the journey</p><h2 className="section-title mt-4">One delivery.<br />A connected effort.</h2><p className="mt-6 max-w-md leading-7 text-muted-foreground">Reliable coordination brings the whole journey together, from planning a shipment to helping with a question along the way.</p></div><div className="space-y-5">{[{icon: Package,title:"Delivery operations",text:"Coordinating shipment details and delivery milestones."},{icon: Globe2,title:"Route coordination",text:"Helping plan domestic and international shipment requirements."},{icon: ShieldCheck,title:"Customer support",text:"A point of contact for shipment questions and next steps."}].map(({icon: Icon,title,text})=><div key={title} className="flex gap-5 border-b pb-5"><Icon size={22} className="mt-1 shrink-0 text-primary" /><div><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm text-muted-foreground">{text}</p></div></div>)}</div></div></section>
    <section className="px-5 pb-24 sm:px-8"><div className="shipping-cta mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-8 rounded-[2rem] p-10 sm:p-14"><h2 className="text-4xl font-medium tracking-tight">Let’s move something<br />forward, together.</h2><Link href="/contact" className="pill-button lime">Meet your next delivery partner <ArrowUpRight size={18} /></Link></div></section>
  </main><SiteFooter /></div>;
}
