import Link from "next/link";
import { ArrowUpRight, Package, ScanLine, Handshake, ShieldCheck, Globe2, Heart } from "lucide-react";
import { NavHeader } from "@/components/public/nav-header";
import { SiteFooter } from "@/components/public/site-footer";
import { getDictionary, getLocale } from "@/i18n/server";
export default async function AboutPage() {
  const a = getDictionary(await getLocale()).about;
  return <div className="min-h-screen"><NavHeader /><main>
    <section className="secondary-hero bg-brand-forest px-5 py-20 text-white sm:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-2"><div><p className="section-kicker !text-[#c7f36b]">{a.heroKicker}</p><h1 className="mt-6 text-5xl font-medium leading-[1.08] tracking-[-.05em] sm:text-6xl">{a.heroTitle[0]}<br />{a.heroTitle[1]}</h1><p className="mt-7 max-w-lg leading-8 text-white/65">{a.heroText}</p></div><div className="about-parcel" aria-hidden="true"><div className="parcel-top" /><div className="parcel-front"><Package size={58} strokeWidth={1} /><span>{a.parcelLabel}</span></div><div className="parcel-side" /><span className="parcel-caption">{a.parcelCaption}</span></div></div></section>
    <section className="mx-auto grid max-w-7xl gap-12 px-5 py-24 sm:px-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="section-kicker">{a.purposeKicker}</p><h2 className="section-title mt-4">{a.purposeTitle[0]}<br />{a.purposeTitle[1]}</h2></div><div><p className="text-xl leading-9">{a.purposeLead}</p><p className="mt-6 leading-8 text-muted-foreground">{a.purposeText}</p></div></section>
    <section className="journey-section px-5 py-24 sm:px-8"><div className="mx-auto max-w-7xl"><p className="section-kicker">{a.principlesKicker}</p><h2 className="section-title mt-4">{a.principlesTitle[0]}<br />{a.principlesTitle[1]}</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{[ScanLine, Heart, Handshake].map((icon, i) => ({ icon, ...a.principles[i] })).map(({icon: Icon,title,text})=><div key={title} className="rounded-3xl border bg-card p-8"><Icon size={28} strokeWidth={1.5} className="text-primary" /><h3 className="mt-8 text-xl font-semibold tracking-tight">{title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{text}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="grid gap-12 lg:grid-cols-2"><div><p className="section-kicker">{a.teamKicker}</p><h2 className="section-title mt-4">{a.teamTitle[0]}<br />{a.teamTitle[1]}</h2><p className="mt-6 max-w-md leading-7 text-muted-foreground">{a.teamText}</p></div><div className="space-y-5">{[Package, Globe2, ShieldCheck].map((icon, i) => ({ icon, ...a.teams[i] })).map(({icon: Icon,title,text})=><div key={title} className="flex gap-5 border-b pb-5"><Icon size={22} className="mt-1 shrink-0 text-primary" /><div><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm text-muted-foreground">{text}</p></div></div>)}</div></div></section>
    <section className="px-5 pb-24 sm:px-8"><div className="shipping-cta mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-8 rounded-[2rem] p-10 sm:p-14"><h2 className="text-4xl font-medium tracking-tight">{a.ctaTitle[0]}<br />{a.ctaTitle[1]}</h2><Link href="/contact" className="pill-button lime">{a.ctaButton} <ArrowUpRight size={18} /></Link></div></section>
  </main><SiteFooter /></div>;
}
