"use client";
import { Suspense, useState } from "react";
import Link from "next/link";
import dynamic from "next/dynamic";
import { useRouter, useSearchParams } from "next/navigation";
import { ArrowUpRight, ArrowRight, Package, Globe2, Truck, Zap, Search, ShieldCheck, MapPin, Check, Headphones } from "lucide-react";
import { NavHeader } from "@/components/public/nav-header";
import { SiteFooter } from "@/components/public/site-footer";
import { SERVICE_LIST } from "@/data/services";
import { isValidTrackingCode } from "../../../convex/lib/tracking";
const DeliveryGlobe = dynamic(() => import("@/components/public/delivery-globe"), { ssr: false });
const icons: Record<string, import("lucide-react").LucideIcon> = { Zap, Package, Truck, Globe: Globe2 };
function Home() {
  const router = useRouter();
  const params = useSearchParams();
  const [code, setCode] = useState("");
  const [error, setError] = useState("");
  function track(event: React.FormEvent) {
    event.preventDefault();
    const value = code.trim().toUpperCase();
    if (!isValidTrackingCode(value)) { setError(value ? "Enter a tracking code in the format DMD-YYYY-NNNNNN." : "Enter your tracking code to continue."); return; }
    setError(""); router.push(`/track/${value}`);
  }
  return <div className="landing min-h-screen"><NavHeader /><main>
    <section className="delivery-hero"><div className="hero-grid mx-auto max-w-7xl px-5 sm:px-8">
      <div className="relative z-10 py-16 lg:py-24"><div className="eyebrow"><span className="h-1.5 w-1.5 rounded-full bg-[#c7f36b]" /> A world of possibilities. Delivered.</div>
        <h1 className="mt-8 text-[clamp(3.5rem,6.5vw,6.2rem)] font-semibold leading-[1.02] tracking-[-.065em]">Small parcels.<br />Big possibilities<span className="text-[#c7f36b]">.</span></h1>
        <p className="mt-7 max-w-md text-base leading-7 text-white/65">Across the city or across the world. Move what matters with thoughtful delivery and a clear view of every step.</p>
        <div className="mt-9 flex flex-wrap items-center gap-5"><Link href="/contact" className="pill-button lime">Let’s get it moving <ArrowUpRight size={18} /></Link><Link href="/services" className="inline-flex items-center gap-2 text-sm font-medium text-white/80">Explore our services <ArrowRight size={16} /></Link></div>
        <div className="mt-12 flex flex-wrap gap-6 text-xs text-white/65"><span className="flex items-center gap-2"><ShieldCheck size={16} className="text-[#c7f36b]" /> Care at every handover</span><span className="flex items-center gap-2"><MapPin size={16} className="text-[#c7f36b]" /> End-to-end visibility</span></div>
      </div>
      <div className="globe-stage relative"><div className="absolute inset-[-7%] lg:inset-[-12%]"><DeliveryGlobe /></div><div className="orbit-label orbit-label-top"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#c7f36b] text-[#123d32]"><Globe2 size={18} /></span><div><b>Closer than ever.</b><small>Connections beyond borders</small></div></div><div className="orbit-label orbit-label-bottom"><span className="grid h-9 w-9 place-items-center rounded-full bg-white/10"><Package size={18} /></span><div><b>From your door. To theirs.</b><small>One connected journey</small></div><Check size={18} className="ml-3 text-[#c7f36b]" /></div><div className="absolute bottom-5 left-0 right-0 text-center font-mono text-[9px] uppercase tracking-[.3em] text-white/40">The Diplomaxdelivery network · visual illustration</div></div>
    </div></section>
    <section id="track" className="tracking-strip scroll-mt-24"><div className="mx-auto grid max-w-7xl items-center gap-6 px-5 py-8 sm:px-8 lg:grid-cols-[.8fr_1.2fr]"><div className="flex items-center gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl border border-current/15"><Package size={23} /></span><div><h2 className="text-xl font-semibold tracking-tight">Something on the way?</h2><p className="mt-1 text-sm text-muted-foreground">Your next update is one tracking code away.</p></div></div><form onSubmit={track} className="min-w-0"><div className="flex gap-2 rounded-2xl border bg-card p-2 shadow-sm"><label htmlFor="tracking-code" className="sr-only">Tracking code</label><input id="tracking-code" autoComplete="off" value={code} onChange={e => { setCode(e.target.value); setError(""); }} placeholder="Enter your tracking code" aria-invalid={!!error} aria-describedby={error ? "tracking-error" : undefined} className="min-w-0 flex-1 bg-transparent px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-primary rounded-lg" /><button className="pill-button forest !rounded-xl !px-5"><Search size={16} /><span className="hidden sm:inline">Track package</span><span className="sm:hidden">Track</span></button></div>{error && <p id="tracking-error" role="alert" className="mt-2 text-sm text-red-600">{error}</p>}{params.get("rateLimited") === "1" && <p role="alert" className="mt-2 text-sm text-red-600">Too many requests. Please wait a minute before trying again.</p>}</form></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="section-kicker">01 / Made to move</p><h2 className="section-title mt-4">Whatever the size.<br />Wherever the destination.</h2></div><p className="max-w-sm text-sm leading-7 text-muted-foreground">A little something for a loved one. Your next big business order. Find a service that fits your journey.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{SERVICE_LIST.map((service, index) => { const Icon = icons[service.icon] ?? Package; return <Link key={service.slug} href={`/services/${service.slug}`} className="service-tile group"><div className="flex items-start justify-between"><span className="service-icon"><Icon size={26} strokeWidth={1.5} /></span><span className="font-mono text-xs opacity-40">0{index + 1}</span></div><h3 className="mt-10 text-xl font-semibold tracking-tight">{service.name}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{service.description}</p><div className="mt-7 flex items-center justify-between border-t pt-5 text-sm font-semibold"><span>Explore service</span><ArrowUpRight size={20} className="transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></div></Link>; })}</div></section>
    <section className="journey-section px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-16 lg:grid-cols-2 lg:items-center"><div className="journey-art"><span className="section-kicker">Every journey matters</span><div className="journey-path"><div className="journey-stop"><Package size={22} /><span>Collected with care</span><Check size={16} /></div><div className="journey-stop"><Truck size={22} /><span>Moving with purpose</span><Check size={16} /></div><div className="journey-stop"><MapPin size={22} /><span>Right where it belongs</span><Check size={16} /></div></div><p className="text-xs text-muted-foreground">A simpler experience, from start to finish.</p></div><div><p className="section-kicker">02 / More care. Less worry.</p><h2 className="section-title mt-4">Great delivery.<br />Even better peace of mind.</h2><div className="mt-9 space-y-7">{[{icon: MapPin, title: "Follow the journey", text: "Access shipment updates and route details in one place, whenever you need them."},{icon: ShieldCheck, title: "The details make the difference", text: "From shipment information to delivery milestones, keep the important details close."},{icon: Headphones, title: "People you can reach", text: "Have a question about your delivery? Connect with our team for a helping hand."}].map(item => <div key={item.title} className="flex gap-4"><item.icon size={21} className="mt-1 shrink-0 text-primary" /><div><h3 className="font-semibold">{item.title}</h3><p className="mt-2 max-w-md text-sm leading-6 text-muted-foreground">{item.text}</p></div></div>)}</div></div></div></section>
    <section className="px-5 py-20 sm:px-8"><div className="shipping-cta mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 rounded-[2rem] p-8 sm:p-14 lg:flex-row lg:items-center"><div><p className="section-kicker !text-[#c7f36b]">Your next move starts here</p><h2 className="mt-4 text-4xl font-medium tracking-[-.045em] sm:text-5xl">Good things are<br />going places.</h2></div><Link href="/contact" className="pill-button lime">Plan your delivery <ArrowUpRight size={20} /></Link></div></section>
  </main><SiteFooter /></div>;
}
export default function HomePage() { return <Suspense fallback={<div className="min-h-screen bg-[#123d32]" />}><Home /></Suspense>; }
